# $NetBSD$
#

DISTNAME=	args_parser-0.1.4
CATEGORIES=	misc

MAINTAINER=	tsutsui@NetBSD.org
HOMEPAGE=	http://shokai.github.io/args_parser/
COMMENT=	Parse ARGV from command line with DSL
LICENSE=	mit

USE_LANGUAGES=	# none

.include "../../lang/ruby/gem.mk"
.include "../../mk/bsd.pkg.mk"
