# $NetBSD: Makefile,v 1.42 2013/02/16 11:23:36 wiz Exp $

DISTNAME=	mplayerthumbs-${_KDE_VERSION}
CATEGORIES=	multimedia
COMMENT=	thumbnail generator for all KDE file managers

.include "../../meta-pkgs/kde4/Makefile.kde4"

.include "../../meta-pkgs/kde4/kde4.mk"

.include "../../x11/kdelibs4/buildlink3.mk"

.include "../../mk/bsd.pkg.mk"
