# $NetBSD: Makefile,v 1.42 2013/02/16 11:23:36 wiz Exp $

DISTNAME=	libkcddb-${_KDE_VERSION}
CATEGORIES=	multimedia
COMMENT=	KDE CDDB library

.include "../../meta-pkgs/kde4/Makefile.kde4"

.include "../../meta-pkgs/kde4/kde4.mk"

.include "../../audio/libmusicbrainz5/buildlink3.mk"
.include "../../x11/kdelibs4/buildlink3.mk"

.include "../../mk/bsd.pkg.mk"
