# $NetBSD: Makefile,v 1.2 2012/06/01 15:47:18 wiz Exp $

DISTNAME=	io-console-0.4.2
CATEGORIES=	devel

MAINTAINER=	pkgsrc-users@NetBSD.org
HOMEPAGE=	https://github.com/nobu/io-console
COMMENT=	Add console capabilities to IO instances

.include "../../lang/ruby/gem.mk"
.include "../../mk/bsd.pkg.mk"
