# $NetBSD$
#

DISTNAME=	hashie-1.2.0
CATEGORIES=	misc

MAINTAINER=	tsutsui@NetBSD.org
HOMEPAGE=	https://github.com/intridea/hashie
COMMENT=	Small collection of tools that make hashes more powerful


LICENSE=	mit

USE_LANGUAGES=	# none

.include "../../lang/ruby/gem.mk"
.include "../../mk/bsd.pkg.mk"
