# $NetBSD: Makefile,v 1.14 2013/01/26 21:38:32 adam Exp $
#

GST_PLUGINS1_NAME=	soup
GST_PLUGINS1_DIRS=	ext/soup

.include "../../multimedia/gst-plugins1-good/Makefile.common"

.include "../../net/libsoup24/buildlink3.mk"
.include "../../mk/bsd.pkg.mk"
