# $NetBSD: Makefile,v 1.42 2013/02/16 11:23:36 wiz Exp $

DISTNAME=	libkcompactdisc-${_KDE_VERSION}
CATEGORIES=	multimedia
COMMENT=	a library for interfacing with CDs

.include "../../meta-pkgs/kde4/Makefile.kde4"

.include "../../mk/bsd.prefs.mk"
.include "options.mk"

.include "../../meta-pkgs/kde4/kde4.mk"

.include "../../x11/kdelibs4/buildlink3.mk"

.include "../../mk/bsd.pkg.mk"
