# $NetBSD$

# used by devel/libevent/Makefile
# used by devel/py-libevent-rpcgen/Makefile

LIBEVENT_VERSION=	2.0.21

DISTNAME=		libevent-${LIBEVENT_VERSION}-stable
MASTER_SITES=		${MASTER_SITE_SOURCEFORGE:=levent/}
