# $NetBSD: Makefile,v 1.38 2013/02/16 11:21:22 wiz Exp $

DISTNAME=	kde-base-artwork-${_KDE_VERSION}
CATEGORIES=	graphics
COMMENT=	KDE KSplash theme

.include "../../meta-pkgs/kde4/Makefile.kde4"

.include "../../meta-pkgs/kde4/kde4.mk"

.include "../../x11/kdelibs4/buildlink3.mk"

.include "../../mk/bsd.pkg.mk"
