# $NetBSD$
#

DISTNAME=	rainbow-1.1.4
CATEGORIES=	misc

MAINTAINER=	tsutsui@NetBSD.org
HOMEPAGE=	https://github.com/sickill/rainbow
COMMENT=	Extends ruby String class enabling coloring text on ANSI terminals
LICENSE=	mit

USE_LANGUAGES=	# none

.include "../../lang/ruby/gem.mk"
.include "../../mk/bsd.pkg.mk"
