# $NetBSD: Makefile,v 1.46 2013/02/16 11:19:55 wiz Exp $

DISTNAME=	nepomuk-widgets-${_KDE_VERSION}
CATEGORIES=	misc
COMMENT=	Nepomuk Meta Data Library

.include "../../meta-pkgs/kde4/Makefile.kde4"

.include "../../meta-pkgs/kde4/kde4.mk"

.include "../../misc/nepomuk-core/buildlink3.mk"
.include "../../x11/kdelibs4/buildlink3.mk"

.include "../../mk/bsd.pkg.mk"
