# $NetBSD: Makefile,v 1.1 2013/04/24 02:20:41 rodent Exp $

PKGNAME=	ispell-ru-io-${RUS_ISPELL_VERSION}
CONFLICTS+=	ispell-russian-io-[0-9]*
MAKE_ENV+=	IO="defined"

.include "../../textproc/ispell-russian/Makefile.common"
