# $NetBSD$
#

DISTNAME=	parallel-0.6.4
CATEGORIES=	misc

MAINTAINER=	tsutsui@NetBSD.org
HOMEPAGE=	https://github.com/grosser/parallel
COMMENT=	Run any kind of code in parallel processes
LICENSE=	mit

USE_LANGUAGES=	# none

.include "../../lang/ruby/gem.mk"
.include "../../mk/bsd.pkg.mk"
