# $NetBSD$

DISTNAME=	text-1.2.1
CATEGORIES=	textproc

MAINTAINER=	obache@NetBSD.org
HOMEPAGE=	https://github.com/threedaymonk/text
COMMENT=	Collection of text algorithms for Ruby
LICENSE=	ruby-license

.include "../../lang/ruby/gem.mk"
.include "../../mk/bsd.pkg.mk"
