# $NetBSD$

DISTNAME=	polib-1.0.3
PKGNAME=	${PYPKGPREFIX}-${DISTNAME:tl}
CATEGORIES=	devel python
MASTER_SITES=	http://cdn.bitbucket.org/izi/polib/downloads/

MAINTAINER=	pkgsrc-users@NetBSD.org
HOMEPAGE=	http://bitbucket.org/izi/polib/
COMMENT=	Python library to parse and manage gettext catalogs
LICENSE=	mit

USE_LANGUAGES=		# empty

PYTHON_VERSIONS_INCLUDE_3X=	yes

.include "../../lang/python/distutils.mk"
.include "../../mk/bsd.pkg.mk"
