# $NetBSD$
#

DISTNAME=	entr-1.9
CATEGORIES=	sysutils
MASTER_SITES=	http://entrproject.org/code/

MAINTAINER=	pkgsrc-users@NetBSD.org
HOMEPAGE=	http://entrproject.org/code/
COMMENT=	Run arbitrary commands when files change
#LICENSE=	# TODO: (see mk/license.mk)

WRKSRC=		${WRKDIR}/eradman-entr-587c18272485
HAS_CONFIGURE=	yes
MAKE_FILE=	Makefile.bsd

.include "../../mk/bsd.pkg.mk"
