# $NetBSD$

DISTNAME=	speaklater-1.3
PKGNAME=	${PYPKGPREFIX}-${DISTNAME}
CATEGORIES=	www python
MASTER_SITES=	http://pypi.python.org/packages/source/s/speaklater/

MAINTAINER=	kleink@NetBSD.org
HOMEPAGE=	http://github.com/mitsuhiko/speaklater
COMMENT=	Implements a lazy string for python useful for use with gettext
LICENSE=	modified-bsd

USE_LANGUAGES=	# empty

.include "../../lang/python/egg.mk"
.include "../../mk/bsd.pkg.mk"
